name=input("enter name\n")
print(name,type(name))
roll=int(input("Enter number\n"))
print(roll,type(roll))
float=float(input("enter float number\n"))
print(float,type(float))
c=input("Enter char\n")
print(c,type(c))
str=input("Enter a string\n")
print(str,type(str))
