file = open("sample.txt", "w")
file.write("Hello World\n")
file.write("Welcome to Python File Handling\n")
lines = ["MANU\n", "PRANATHI2\n", "CHERRY\n"]
file.writelines(lines)
file.close()
file = open("sample.txt", "r")
print("Using read():")
print(file.read())
file.close()
file = open("sample.txt", "r")
print("\nUsing readline():")
print(file.readline())  
print(file.readline()) 
file.close()
file = open("sample.txt", "r")
print("\nUsing readlines():")
print(file.readlines())
file.close()
